// 슬라이드 p10-v9-partial — 생성기가 쓸 조각(손으로 쓴 대역), C# 9.0
// <auto-generated/> stand-in: a generator would write this file.
partial class Parser
{
    public partial bool TryParse(string s, out int value)
        => int.TryParse(s, out value);
    internal partial string Describe() => "Parser(int)";
    public virtual partial string GetName() => "parser";
}
