// 슬라이드 p14-v13-pp-gen — 생성기가 쓸 조각(손으로 쓴 대역), C# 13.0
// <auto-generated/> stand-in: a generator would write this file.
using System;

partial class Person
{
    public event Action<string> Changed;
    private string name;
    private int age;
    private void Raise(string what) => Changed?.Invoke(what);

    public partial string Name
    {
        get => name;
        set { if (name != value) { name = value; Raise("Name"); } }
    }
    public partial int Age
    {
        get => age;
        set { if (age != value) { age = value; Raise("Age"); } }
    }
}
